// <auto-generated />
using System;
using FinPlanner360.Data.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FinPlanner360.Data.Migrations.FinPlanner360Db
{
    [DbContext(typeof(FinPlanner360DbContext))]
    partial class FinPlanner360DbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("FinPlanner360.Business.Models.Budget", b =>
                {
                    b.Property<Guid>("BudgetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("UniqueIdentifier")
                        .HasColumnName("BudgetId");

                    b.Property<decimal>("Amount")
                        .HasPrecision(2)
                        .HasColumnType("Money")
                        .HasColumnName("Amount");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("UniqueIdentifier")
                        .HasColumnName("CategoryId");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("DateTime")
                        .HasColumnName("CreatedDate");

                    b.Property<Guid>("UserId")
                        .HasColumnType("UniqueIdentifier")
                        .HasColumnName("UserId");

                    b.HasKey("BudgetId")
                        .HasName("BudgetsPK");

                    b.HasIndex("CategoryId");

                    b.HasIndex("UserId")
                        .HasDatabaseName("BudgetsUserIdIX");

                    b.ToTable("Budgets", (string)null);
                });

            modelBuilder.Entity("FinPlanner360.Business.Models.Category", b =>
                {
                    b.Property<Guid>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("UniqueIdentifier")
                        .HasColumnName("CategoryId");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("DateTime")
                        .HasColumnName("CreatedDate");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("Varchar")
                        .HasColumnName("Description")
                        .UseCollation("Latin1_General_CI_AI");

                    b.Property<int>("Type")
                        .HasColumnType("TinyInt")
                        .HasColumnName("Type");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("UniqueIdentifier")
                        .HasColumnName("UserId");

                    b.HasKey("CategoryId")
                        .HasName("CategoriesPK");

                    b.HasIndex("UserId")
                        .HasDatabaseName("CategoriesUserIdIX");

                    b.ToTable("Categories", (string)null);
                });

            modelBuilder.Entity("FinPlanner360.Business.Models.GeneralBudget", b =>
                {
                    b.Property<Guid>("GeneralBudgetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("UniqueIdentifier")
                        .HasColumnName("GeneralBudgetId");

                    b.Property<decimal?>("Amount")
                        .HasPrecision(2)
                        .HasColumnType("Money")
                        .HasColumnName("Amount");

                    b.Property<decimal?>("Percentage")
                        .HasPrecision(0)
                        .HasColumnType("Money")
                        .HasColumnName("Percentage");

                    b.Property<Guid>("UserId")
                        .HasColumnType("UniqueIdentifier")
                        .HasColumnName("UserId");

                    b.HasKey("GeneralBudgetId")
                        .HasName("GeneralBudgetsPK");

                    b.HasIndex("UserId")
                        .HasDatabaseName("GenerealBudgetsUserIdIX");

                    b.ToTable("GeneralBudgets", (string)null);
                });

            modelBuilder.Entity("FinPlanner360.Business.Models.Transaction", b =>
                {
                    b.Property<Guid>("TransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("UniqueIdentifier")
                        .HasColumnName("TransactionId");

                    b.Property<decimal>("Amount")
                        .HasPrecision(2)
                        .HasColumnType("Money")
                        .HasColumnName("Amount");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("UniqueIdentifier")
                        .HasColumnName("CategoryId");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("DateTime")
                        .HasColumnName("CreatedDate");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("Varchar")
                        .HasColumnName("Description")
                        .UseCollation("Latin1_General_CI_AI");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("SmallDateTime")
                        .HasColumnName("TransactionDate");

                    b.Property<Guid>("UserId")
                        .HasColumnType("UniqueIdentifier")
                        .HasColumnName("UserId");

                    b.HasKey("TransactionId")
                        .HasName("TransactionsPK");

                    b.HasIndex("CategoryId");

                    b.HasIndex("UserId")
                        .HasDatabaseName("TransactionsUserIdIX");

                    b.ToTable("Transactions", (string)null);
                });

            modelBuilder.Entity("FinPlanner360.Business.Models.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("UniqueIdentifier")
                        .HasColumnName("UserId");

                    b.Property<Guid>("AuthenticationId")
                        .HasColumnType("UniqueIdentifier")
                        .HasColumnName("AuthenticationId");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("Varchar")
                        .HasColumnName("Email")
                        .UseCollation("Latin1_General_CI_AI");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("Varchar")
                        .HasColumnName("Name")
                        .UseCollation("Latin1_General_CI_AI");

                    b.HasKey("UserId")
                        .HasName("UsersPK");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("FinPlanner360.Business.Models.Budget", b =>
                {
                    b.HasOne("FinPlanner360.Business.Models.Category", "Category")
                        .WithMany("Budgeties")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("BudgetsCategoryFK");

                    b.HasOne("FinPlanner360.Business.Models.User", "User")
                        .WithMany("Budgets")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("BudgetsUserFK");

                    b.Navigation("Category");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FinPlanner360.Business.Models.Category", b =>
                {
                    b.HasOne("FinPlanner360.Business.Models.User", "User")
                        .WithMany("Categories")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("CategoriesUserFK");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FinPlanner360.Business.Models.GeneralBudget", b =>
                {
                    b.HasOne("FinPlanner360.Business.Models.User", "User")
                        .WithMany("GeneralBudgets")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("GenerealBudgetsUserFK");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FinPlanner360.Business.Models.Transaction", b =>
                {
                    b.HasOne("FinPlanner360.Business.Models.Category", "Category")
                        .WithMany("Transactions")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("TransactionsCategoryFK");

                    b.HasOne("FinPlanner360.Business.Models.User", "User")
                        .WithMany("Transactions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("TransactionsUserFK");

                    b.Navigation("Category");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FinPlanner360.Business.Models.Category", b =>
                {
                    b.Navigation("Budgeties");

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("FinPlanner360.Business.Models.User", b =>
                {
                    b.Navigation("Budgets");

                    b.Navigation("Categories");

                    b.Navigation("GeneralBudgets");

                    b.Navigation("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
